name: server
description: A server app using the shelf package and Docker.
version: 1.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  envify: ^2.0.2
  jwt_decode: ^0.3.1
  mime: ^1.0.2
  path_provider: ^2.0.11
  shelf: ^1.1.0
  shelf_multipart: ^1.0.0
  shelf_router: ^1.0.0
  supabase: ^0.3.4+1

dev_dependencies:
  build_runner: ^2.1.11
  dart_jsonwebtoken: ^2.4.1
  envify_generator: ^2.0.2
  http: ^0.13.0
  lints: ^1.0.0
  test: ^1.15.0
  test_process: ^2.0.0